let html = [
  "HTML APIs",
  "HTML Geolocation",
  "HTML Drag/Drop",
  "HTML Web Storage",
  "HTML Web Workers",
  "HTML SSE",
  "HTML Media",
  "HTML Media",
  "HTML Video",
  "HTML Audio",
  "HTML Plug-ins",
  "HTML YouTube",
  "HTML Tutorial",
  "HTML HOME",
  "HTML Introduction",
  "HTML Editors",
  "HTML Basic",
  "HTML Elements",
  "HTML Attributes",
  "HTML Headings",
  "HTML Paragraphs",
  "HTML Styles",
  "HTML Formatting",
  "HTML Quotations",
  "HTML Comments",
  "HTML Colors",
  "HTML CSS",
  "HTML Links",
  "HTML Images",
  "HTML Favicon",
  "HTML Tables",
  "HTML Lists",
  "HTML Block & Inline",
  "HTML Classes",
  "HTML Id",
  "HTML Iframes",
  "HTML JavaScript",
  "HTML File Paths",
  "HTML Head",
  "HTML Layout",
  "HTML Responsive",
  "HTML Computercode",
  "HTML Semantics",
  "HTML Style Guide",
  "HTML Entities",
  "HTML Symbols",
  "HTML Emojis",
  "HTML Charset",
  "HTML URL Encode",
  "HTML vs XHTML",
];

 let css = [
  "CSS Tutorial",
  "CSS HOME",
  "CSS Introduction",
  "CSS Syntax",
  "CSS Selectors",
  "CSS How To",
  "CSS Comments",
  "CSS Colors",
  "CSS Backgrounds",
  "CSS Borders",
  "CSS Margins",
  "CSS Padding",
  "CSS Height/Width",
  "CSS Box Model",
  "CSS Outline",
  "CSS Text",
  "CSS Fonts",
  "CSS Icons",
  "CSS Links",
  "CSS Lists",
  "CSS Tables",
  "CSS Display",
  "CSS Max-width",
  "CSS Position",
  "CSS Z-index",
  "CSS Overflow",
  "CSS Float",
  "CSS Inline-block",
  "CSS Align",
  "CSS Combinators",
  "CSS Pseudo-class",
  "CSS Pseudo-element",
  "CSS Opacity",
  "CSS Navigation Bar",
  "CSS Dropdowns",
  "CSS Image Gallery",
  "CSS Image Sprites",
  "CSS Attr Selectors",
  "CSS Forms",
  "CSS Counters",
  "CSS Website Layout",
  "CSS Units",
  "CSS Specificity",
  "CSS !important",
  "CSS Math Functions",
  "CSS Advanced",
  "CSS Rounded Corners",
  "CSS Border Images",
  "CSS Backgrounds",
  "CSS Colors",
  "CSS Color Keywords",
  "CSS Gradients",
  "CSS Shadows",
  "CSS Text Effects",
  "CSS Web Fonts",
  "CSS 2D Transforms",
  "CSS 3D Transforms",
  "CSS Transitions",
  "CSS Animations",
  "CSS Tooltips",
  "CSS Style Images",
  "CSS Image Reflection",
  "CSS object-fit",
  "CSS object-position",
  "CSS Masking",
  "CSS Buttons",
  "CSS Pagination",
  "CSS Multiple Columns",
  "CSS User Interface",
  "CSS Variables",
  "CSS Box Sizing",
  "CSS Media Queries",
  "CSS MQ Examples",
  "CSS Flexbox",
  "CSS Responsive",
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "CSS Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "CSS SASS",
  "SASS Tutorial",
  "CSS Examples",
  "CSS Templates",
  "CSS Examples",
  "CSS Snippets",
  "CSS Quiz",
  "CSS Exercises",
  "CSS Certificate",
  "CSS References",
  "CSS Reference",
  "CSS Selectors",
  "CSS Functions",
  "CSS Reference Aural",
  "CSS Web Safe Fonts",
  "CSS Animatable",
  "CSS Units",
  "CSS PX-EM Converter",
  "CSS Colors",
  "CSS Color Values",
  "CSS Default Values",
  "CSS Browser Support",
];



export {html, css}