let html = [
  "HTML APIs",
  "HTML Geolocation",
  "HTML Drag/Drop",
  "HTML Web Storage",
  "HTML Web Workers",
  "HTML SSE",
  "HTML Media",
  "HTML Media",
  "HTML Video",
  "HTML Audio",
  "HTML Plug-ins",
  "HTML YouTube",
  "HTML Tutorial",
  "HTML HOME",
  "HTML Introduction",
  "HTML Editors",
  "HTML Basic",
  "HTML Elements",
  "HTML Attributes",
  "HTML Headings",
  "HTML Paragraphs",
  "HTML Styles",
  "HTML Formatting",
  "HTML Quotations",
  "HTML Comments",
  "HTML Colors",
  "HTML CSS",
  "HTML Links",
  "HTML Images",
  "HTML Favicon",
  "HTML Tables",
  "HTML Lists",
  "HTML Block & Inline",
  "HTML Classes",
  "HTML Id",
  "HTML Iframes",
  "HTML JavaScript",
  "HTML File Paths",
  "HTML Head",
  "HTML Layout",
  "HTML Responsive",
  "HTML Computercode",
  "HTML Semantics",
  "HTML Style Guide",
  "HTML Entities",
  "HTML Symbols",
  "HTML Emojis",
  "HTML Charset",
  "HTML URL Encode",
  "HTML vs XHTML",
];

let css = [
  "CSS Tutorial",
  "CSS HOME",
  "CSS Introduction",
  "CSS Syntax",
  "CSS Selectors",
  "CSS How To",
  "CSS Comments",
  "CSS Colors",
  "CSS Backgrounds",
  "CSS Borders",
  "CSS Margins",
  "CSS Padding",
  "CSS Height/Width",
  "CSS Box Model",
  "CSS Outline",
  "CSS Text",
  "CSS Fonts",
  "CSS Icons",
  "CSS Links",
  "CSS Lists",
  "CSS Tables",
  "CSS Display",
  "CSS Max-width",
  "CSS Position",
  "CSS Z-index",
  "CSS Overflow",
  "CSS Float",
  "CSS Inline-block",
  "CSS Align",
  "CSS Combinators",
  "CSS Pseudo-class",
  "CSS Pseudo-element",
  "CSS Opacity",
  "CSS Navigation Bar",
  "CSS Dropdowns",
  "CSS Image Gallery",
  "CSS Image Sprites",
  "CSS Attr Selectors",
  "CSS Forms",
  "CSS Counters",
  "CSS Website Layout",
  "CSS Units",
  "CSS Specificity",
  "CSS !important",
  "CSS Math Functions",
  "CSS Advanced",
  "CSS Rounded Corners",
  "CSS Border Images",
  "CSS Backgrounds",
  "CSS Colors",
  "CSS Color Keywords",
  "CSS Gradients",
  "CSS Shadows",
  "CSS Text Effects",
  "CSS Web Fonts",
  "CSS 2D Transforms",
  "CSS 3D Transforms",
  "CSS Transitions",
  "CSS Animations",
  "CSS Tooltips",
  "CSS Style Images",
  "CSS Image Reflection",
  "CSS object-fit",
  "CSS object-position",
  "CSS Masking",
  "CSS Buttons",
  "CSS Pagination",
  "CSS Multiple Columns",
  "CSS User Interface",
  "CSS Variables",
  "CSS Box Sizing",
  "CSS Media Queries",
  "CSS MQ Examples",
  "CSS Flexbox",
  "CSS Responsive",
  "RWD Intro",
  "RWD Viewport",
  "RWD Grid View",
  "RWD Media Queries",
  "RWD Images",
  "RWD Videos",
  "RWD Frameworks",
  "RWD Templates",
  "CSS Grid",
  "Grid Intro",
  "Grid Container",
  "Grid Item",
  "CSS SASS",
  "SASS Tutorial",
  "CSS Examples",
  "CSS Templates",
  "CSS Examples",
  "CSS Snippets",
  "CSS Quiz",
  "CSS Exercises",
  "CSS Certificate",
  "CSS References",
  "CSS Reference",
  "CSS Selectors",
  "CSS Functions",
  "CSS Reference Aural",
  "CSS Web Safe Fonts",
  "CSS Animatable",
  "CSS Units",
  "CSS PX-EM Converter",
  "CSS Colors",
  "CSS Color Values",
  "CSS Default Values",
  "CSS Browser Support",
];

let js = [
  "JS Introduction",
  "JS Statements",
  "JS Syntax",
  "JS Comments",
  "JS Variables",
  "JS Let",
  "JS Const",
  "JS Operators",
  "JS Arithmetic",
  "JS Assignment",
  "JS Data Types",
  "JS Functions",
  "JS Objects",
  "JS Events",
  "JS Strings",
  "JS String Methods",
  "JS String Search",
  "JS String Templates",
  "JS Numbers",
  "JS Number Methods",
  "JS Arrays",
  "JS Array Methods",
  "JS Array Sort",
  "JS Array Iteration",
  "JS Array Const",
  "JS Dates",
  "JS Date Formats",
  "JS Date Get Methods",
  "JS Date Set Methods",
  "JS Math",
  "JS Random",
  "JS Booleans",
  "JS Comparisons",
  "JS If Else",
  "JS Switch",
  "JS Loop For",
  "JS Loop For In",
  "JS Loop For Of",
  "JS Loop While",
  "JS Break",
  "JS Iterables",
  "JS Sets",
  "JS Maps",
  "JS Typeof",
  "JS Type Conversion",
  "JS Bitwise",
  "JS RegExp",
  "JS Errors",
  "JS Scope",
  "JS Hoisting",
  "JS Strict Mode",
  "JS this Keyword",
  "JS Arrow Function",
  "JS Classes",
  "JS Modules",
  "JS JSON",
  "JS Debugging",
  "JS Style Guide",
  "JS Best Practices",
  "JS Mistakes",
  "JS Performance",
  "JS Reserved Words",
  "JS Versions",
  "JS Versions",
  "JS 2009 (ES5)",
  "JS 2015 (ES6)",
  "JS 2016",
  "JS 2017",
  "JS 2018",
  "JS IE / Edge",
  "JS History",
  "JS Objects",
  "Object Definitions",
  "Object Properties",
  "Object Methods",
  "Object Display",
  "Object Accessors",
  "Object Constructors",
  "Object Prototypes",
  "Object Iterables",
  "Object Sets",
  "Object Maps",
  "Object Reference",
  "JS Functions",
  "Function Definitions",
  "Function Parameters",
  "Function Invocation",
  "Function Call",
  "Function Apply",
  "Function Bind",
  "Function Closures",
  "JS Classes",
  "Class Intro",
  "Class Inheritance",
  "Class Static",
  "JS Async",
  "JS Callbacks",
  "JS Asynchronous",
  "JS Promises",
  "JS Async/Await",
  "JS HTML DOM",
  "DOM Intro",
  "DOM Methods",
  "DOM Document",
  "DOM Elements",
  "DOM HTML",
  "DOM Forms",
  "DOM CSS",
  "DOM Animations",
  "DOM Events",
  "DOM Event Listener",
  "DOM Navigation",
  "DOM Nodes",
  "DOM Collections",
  "DOM Node Lists",
  "JS Browser BOM",
  "JS Window",
  "JS Screen",
  "JS Location",
  "JS History",
  "JS Navigator",
  "JS Popup Alert",
  "JS Timing",
  "JS Cookies",
  "JS Web APIs",
  "Web API Intro",
  "Web Forms API",
  "Web History API",
  "Web Storage API",
  "Web Worker API",
  "Web Fetch API",
  "Web Geolocation API",
  "JS AJAX",
  "AJAX Intro",
  "AJAX XMLHttp",
  "AJAX Request",
  "AJAX Response",
  "AJAX XML File",
  "AJAX PHP",
  "AJAX ASP",
  "AJAX Database",
  "AJAX Applications",
  "AJAX Examples",
  "JS JSON",
  "JSON Intro",
  "JSON Syntax",
  "JSON vs XML",
  "JSON Data Types",
  "JSON Parse",
  "JSON Stringify",
  "JSON Objects",
  "JSON Arrays",
  "JSON Server",
  "JSON PHP",
  "JSON HTML",
  "JSON JSONP",
  "JS vs jQuery",
  "jQuery Selectors",
  "jQuery HTML",
  "jQuery CSS",
  "jQuery DOM",
  "JS Graphics",
  "JS Graphics",
  "JS Canvas",
  "JS Plotly",
  "JS Chart.js",
  "JS Google Chart",
  "JS D3.js",
];

let react = [
  "React Tutorial",
  "React Home",
  "React Intro",
  "React Get Started",
  "React ES6",
  "React Render HTML",
  "React JSX",
  "React Components",
  "React Class",
  "React Props",
  "React Events",
  "React Conditionals",
  "React Lists",
  "React Forms",
  "React Router",
  "React Memo",
  "React CSS Styling",
  "React Sass Styling",
  "React Hooks",
  "What is a Hook?",
  "useState",
  "useEffect",
  "useContext",
  "useRef",
  "useReducer",
  "useCallback",
  "useMemo",
  "Custom Hooks",
];

export { html, css, js, react };
